version: '3.8'

services:
  transcriptdemo:
    image: asterisk-ari-stream
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 setup.py "]
    ports:
      - 5678:5678
