version: '3.8'

services:
  transcriptdemo:
    image: asterisk-ari-stream
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 setup.py install "]
    ports:
      - 5678:5678
      - 5039:5039
      - 12222:12222